### ISSUE TITLE
some trouble about llvm

### ISSUE THREAD

**Issue by hzhao1997** [jefflgaol/Install-Packages-Jetson-ARM-Family#1]
I am trying to install llvm and numba on my jetson nao. I follow your instructions and I run the command line "sudo make install". Unfortunately, I get the error:

    CMake Error at docs/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/wan_na/llvm-7.0.1.src/llvm_build_dir/docs/ocamldoc/html/.".
Call Stack (most recent call first):
  cmake_install.cmake:76 (include)
Makefile:139: recipe for target 'install' failed

Could you tell me how to solve it? Thanks~

**Comment by gumdropsteve** [comment]
I'm having an issue with llvm install as well. Everything works until;
```
sudo pip3 install llvmlite
```

at which point I get these errors. Here's the output;
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting llvmlite
  Downloading llvmlite-0.34.0.tar.gz (107 kB)
     |████████████████████████████████| 107 kB 2.7 MB/s 
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l_xmnb6o
       cwd: /tmp/pip-install-gfljw7_a/llvmlite/
  Complete output (15 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py
  LLVM version... 7.0.1
  
  Traceback (most recent call last):
    File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 143, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-glh91jj3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite
         cwd: /tmp/pip-install-gfljw7_a/llvmlite/
    Complete output (18 lines):
    running install
    running build
    got version from file /tmp/pip-install-gfljw7_a/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py
    LLVM version... 7.0.1
    
    Traceback (most recent call last):
      File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 143, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-glh91jj3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite Check the logs for full command output.
```

Any thoughts @jefflgaol?

**Comment by gumdropsteve** [comment]
> I'm having an issue with llvm install as well. Everything works until;
> 
> ```
> sudo pip3 install llvmlite
> ```
> 
> at which point I get these errors.
> 
> Any thoughts @jefflgaol?

#### Update
resolved by updating to v 9.0.1 -- https://gist.github.com/gumdropsteve/c3bd317f44b24ea74930e95a0a9913e5

**Comment by jefflgaol** [comment]
> ```
>  I am trying to install llvm and numba on my jetson nao. I follow your instructions and I run the command line "sudo make install". Unfortunately, I get the error:
> 
> CMake Error at docs/cmake_install.cmake:41 (file):
> ```
> 
> file INSTALL cannot find
> "/home/wan_na/llvm-7.0.1.src/llvm_build_dir/docs/ocamldoc/html/.".
> Call Stack (most recent call first):
> cmake_install.cmake:76 (include)
> Makefile:139: recipe for target 'install' failed
> 
> Could you tell me how to solve it? Thanks~

Did you check whether the folder "/home/wan_na/llvm-7.0.1.src/llvm_build_dir/docs/ocamldoc/html/" exist in your computer? If not, maybe the extraction process is incomplete.

**Comment by jefflgaol** [comment]
> I'm having an issue with llvm install as well. Everything works until;
> 
> ```
> sudo pip3 install llvmlite
> ```
> 
> at which point I get these errors. Here's the output;
> 
> ```
> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> Collecting llvmlite
>   Downloading llvmlite-0.34.0.tar.gz (107 kB)
>      |████████████████████████████████| 107 kB 2.7 MB/s 
> Building wheels for collected packages: llvmlite
>   Building wheel for llvmlite (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l_xmnb6o
>        cwd: /tmp/pip-install-gfljw7_a/llvmlite/
>   Complete output (15 lines):
>   running bdist_wheel
>   /usr/bin/python3 /tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py
>   LLVM version... 7.0.1
>   
>   Traceback (most recent call last):
>     File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 191, in <module>
>       main()
>     File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 181, in main
>       main_posix('linux', '.so')
>     File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 143, in main_posix
>       raise RuntimeError(msg)
>   RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
>   Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
>   
>   error: command '/usr/bin/python3' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for llvmlite
>   Running setup.py clean for llvmlite
> Failed to build llvmlite
> Installing collected packages: llvmlite
>     Running setup.py install for llvmlite ... error
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-glh91jj3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite
>          cwd: /tmp/pip-install-gfljw7_a/llvmlite/
>     Complete output (18 lines):
>     running install
>     running build
>     got version from file /tmp/pip-install-gfljw7_a/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
>     running build_ext
>     /usr/bin/python3 /tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py
>     LLVM version... 7.0.1
>     
>     Traceback (most recent call last):
>       File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 191, in <module>
>         main()
>       File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 181, in main
>         main_posix('linux', '.so')
>       File "/tmp/pip-install-gfljw7_a/llvmlite/ffi/build.py", line 143, in main_posix
>         raise RuntimeError(msg)
>     RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
>     Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
>     
>     error: command '/usr/bin/python3' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gfljw7_a/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-glh91jj3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite Check the logs for full command output.
> ```
> 
> Any thoughts @jefflgaol?

I see. As in https://pypi.org/project/llvmlite/, I found that the latest llvmlite doesn't support the llvm 7. However, you can downgrade your llvm to version 0.29.0 - 0.32.0 which supports llvm 7.
