### ISSUE TITLE
Numba 0.53 requires LLVM >= 9

### ISSUE THREAD

**Issue by papalotis** [jefflgaol/Install-Packages-Jetson-ARM-Family#4]
Today I tried to install numba accroding to the installation instructions and simply using `pip install numba` failed with a message saying that llvm version 9 or 10 was not found. The numba version should be pinned in the instructions (in the same way that llvmlite is)

**Comment by papalotis** [comment]
or the llvm version can be updated (with all the testing and verifications that this implies). I am happy to use a previous version of numba

**Comment by andife** [comment]
Maybe: https://bagustris.wordpress.com/2020/07/09/how-to-install-numba-and-librosa-in-jetson-agx-xavier-ubuntu-18-04/ helps

**Comment by papalotis** [comment]
yeah in the end I got it working with llvm==9, higher versions did not with llvmlite IIRC. after that numba and llvmlite worked just fine, I will look into which llvm version I got working and post a link
