### ISSUE TITLE
sudo pip3 install numba not working

### ISSUE THREAD

**Issue by sanketh1691** [jefflgaol/Install-Packages-Jetson-ARM-Family#6]
After installing llvmlite with LLVM-7.0.1, if we use just pip3 install numba, it is extracting the latest version of numba and failing to build. If we specify any particular version such as 0.41.0 for numba, it is still failing. Not able to find anywhere else on how to install numba with LLVM 7.0.1. It would be of great help, if you can guide me to resolve this.

**Comment by fffonceca** [comment]
Did u follow these instructions? [link](https://bagustris.wordpress.com/2020/07/09/how-to-install-numba-and-librosa-in-jetson-agx-xavier-ubuntu-18-04/)
Try out and tell me how its going.

**Comment by jefflgaol** [comment]
Already updated the instruction based on Pull Request by epicmario7133.
